# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*'] # Tu peux spécifier des domaines spécifiques ici
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: ~
        allow_credentials: false
