# config/packages/nelmio_security.yaml
nelmio_security:
    # Évite le framing du site entier
    clickjacking:
        paths:
            '^/.*': DENY

    # Désactive le sniffing de type de contenu pour les ressources de script
    content_type:
        nosniff: true

    # Active la protection XSS avec le mode blocage
    xss_protection:
        enabled: true
        mode_block: true

    # Configure la politique de l'en-tête de référence
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    csp:
        enabled: true
        enforce:
            default-src:
                - "'self'"
            script-src:
                - "'self'"
                - "https://ajax.googleapis.com" 
                - "https://stackpath.bootstrapcdn.com" 
                - "https://cdnjs.cloudflare.com"  
                - "'unsafe-inline'"  
            style-src:
                - "'self'"
                - "https://fonts.googleapis.com"  
                - "https://stackpath.bootstrapcdn.com"  
                - "https://cdnjs.cloudflare.com" 
                - "'unsafe-inline'"  
            img-src:
                - "'self'"
                - "data:"
                - "https://fonts.googleapis.com" 
            connect-src:
                - "'self'"
            font-src:
                - "'self'"
                - "https://fonts.gstatic.com"  
                - "https://cdnjs.cloudflare.com" 
            object-src:
                - "'none'"
            media-src:
                - "'self'"
            frame-ancestors:
                - "'none'"
            base-uri:
                - "'self'"
            form-action:
                - "'self'"
                - "https://arcane-peak-89557-1b8ef9e04fef.herokuapp.com"
            frame-src:
                - "https://www.google.com/"
