# Route pour le domaine avec www
"https://www.{default}/":
  type: upstream
  upstream: "app:http"

# Redirection du domaine sans www vers le domaine avec www
"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

# Redirection de HTTP vers HTTPS
"http://{default}/":
  type: redirect
  to: "https://www.{default}/"
